-- MySQL Script generated by MySQL Workbench
-- Sun Aug  2 17:29:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Comprador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comprador` (
  `Nom` VARCHAR(45) NULL,
  `DNI` CHAR(9) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quadre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Quadre` (
  `idQuadre` INT NOT NULL,
  `Preu` DECIMAL NOT NULL,
  `Autor` VARCHAR(45) NULL,
  `Comprador_DNI` CHAR(9) NULL,
  PRIMARY KEY (`idQuadre`),
  INDEX `fk_Quadre_Comprador_idx` (`Comprador_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Quadre_Comprador`
    FOREIGN KEY (`Comprador_DNI`)
    REFERENCES `mydb`.`Comprador` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuari` (
  `idUsuari` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasenya` CHAR(11) NOT NULL,
  PRIMARY KEY (`idUsuari`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Video` (
  `descripcio` VARCHAR(45) NULL,
  `titol` VARCHAR(45) NULL,
  `url` VARCHAR(45) NOT NULL,
  `idVideo` VARCHAR(45) NOT NULL,
  `Usuari_idUsuari` INT NOT NULL,
  PRIMARY KEY (`idVideo`),
  INDEX `fk_Video_Usuari1_idx` (`Usuari_idUsuari` ASC) VISIBLE,
  CONSTRAINT `fk_Video_Usuari1`
    FOREIGN KEY (`Usuari_idUsuari`)
    REFERENCES `mydb`.`Usuari` (`idUsuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT NOT NULL,
  `direccio` VARCHAR(45) NOT NULL,
  `Llibres publicats` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuari` (
  `idUsuari` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasenya` CHAR(11) NOT NULL,
  PRIMARY KEY (`idUsuari`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Llibres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Llibres` (
  `idLlibres` INT NOT NULL,
  `Unitats` INT UNSIGNED NULL,
  `Preu` DECIMAL UNSIGNED NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  `Usuari_idUsuari` INT NOT NULL,
  PRIMARY KEY (`idLlibres`),
  INDEX `fk_Llibres_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  INDEX `fk_Llibres_Usuari1_idx` (`Usuari_idUsuari` ASC) VISIBLE,
  CONSTRAINT `fk_Llibres_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Llibres_Usuari1`
    FOREIGN KEY (`Usuari_idUsuari`)
    REFERENCES `mydb`.`Usuari` (`idUsuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `idFactura` INT NOT NULL,
  `quantitat` INT UNSIGNED NOT NULL,
  `Llibres_idLlibres` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Llibres1_idx` (`Llibres_idLlibres` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Llibres1`
    FOREIGN KEY (`Llibres_idLlibres`)
    REFERENCES `mydb`.`Llibres` (`idLlibres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuari` (
  `idUsuari` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasenya` CHAR(11) NOT NULL,
  PRIMARY KEY (`idUsuari`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fotografies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fotografies` (
  `idFotografies` INT NOT NULL,
  `adreça` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `Usuari_idUsuari` INT NOT NULL,
  PRIMARY KEY (`idFotografies`),
  INDEX `fk_Fotografies_Usuari1_idx` (`Usuari_idUsuari` ASC) VISIBLE,
  CONSTRAINT `fk_Fotografies_Usuari1`
    FOREIGN KEY (`Usuari_idUsuari`)
    REFERENCES `mydb`.`Usuari` (`idUsuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Amics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Amics` (
  `idAmics` INT NOT NULL,
  `conegut` VARCHAR(45) NOT NULL,
  `Usuari_idUsuari` INT NOT NULL,
  `Usuari_idUsuari1` INT NOT NULL,
  PRIMARY KEY (`idAmics`),
  INDEX `fk_Amics_Usuari1_idx` (`Usuari_idUsuari` ASC) VISIBLE,
  INDEX `fk_Amics_Usuari2_idx` (`Usuari_idUsuari1` ASC) VISIBLE,
  CONSTRAINT `fk_Amics_Usuari1`
    FOREIGN KEY (`Usuari_idUsuari`)
    REFERENCES `mydb`.`Usuari` (`idUsuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Amics_Usuari2`
    FOREIGN KEY (`Usuari_idUsuari1`)
    REFERENCES `mydb`.`Usuari` (`idUsuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveïdor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveïdor` (
  `nom` VARCHAR(45) NOT NULL,
  `telefon` INT UNSIGNED NOT NULL,
  `fax` INT UNSIGNED NULL,
  `NIF` CHAR(9) NOT NULL,
  PRIMARY KEY (`NIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adreça`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adreça` (
  `idAdreça` INT NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` INT UNSIGNED NOT NULL,
  `pis` VARCHAR(45) NULL,
  `porta` INT UNSIGNED NOT NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `codipostal` INT UNSIGNED NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `Proveïdor_idProveïdor` INT NOT NULL,
  `Proveïdor_NIF` CHAR(9) NOT NULL,
  PRIMARY KEY (`idAdreça`),
  INDEX `fk_Adreça_Proveïdor1_idx` (`Proveïdor_NIF` ASC) VISIBLE,
  CONSTRAINT `fk_Adreça_Proveïdor1`
    FOREIGN KEY (`Proveïdor_NIF`)
    REFERENCES `mydb`.`Proveïdor` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `idClients` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adreçapostal` VARCHAR(45) NOT NULL,
  `telefon` INT UNSIGNED NOT NULL,
  `dataregistre` DATETIME(14) NOT NULL,
  `recomenat` VARCHAR(45) NULL,
  PRIMARY KEY (`idClients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleat` (
  `idEmpleat` INT NOT NULL,
  PRIMARY KEY (`idEmpleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ulleres` (
  `idUlleres` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `graduacio` DECIMAL UNSIGNED NOT NULL,
  `montura` VARCHAR(45) NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_vidre` VARCHAR(45) NOT NULL,
  `preu` DECIMAL NOT NULL,
  `Proveïdor_idProveïdor` INT UNSIGNED NOT NULL,
  `Clients_idClients` INT NOT NULL,
  `Empleat_idEmpleat` INT NOT NULL,
  `Proveïdor_NIF` CHAR(9) NOT NULL,
  PRIMARY KEY (`idUlleres`),
  INDEX `fk_Ulleres_Clients1_idx` (`Clients_idClients` ASC) VISIBLE,
  INDEX `fk_Ulleres_Empleat1_idx` (`Empleat_idEmpleat` ASC) VISIBLE,
  INDEX `fk_Ulleres_Proveïdor1_idx` (`Proveïdor_NIF` ASC) VISIBLE,
  CONSTRAINT `fk_Ulleres_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `mydb`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ulleres_Empleat1`
    FOREIGN KEY (`Empleat_idEmpleat`)
    REFERENCES `mydb`.`Empleat` (`idEmpleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ulleres_Proveïdor1`
    FOREIGN KEY (`Proveïdor_NIF`)
    REFERENCES `mydb`.`Proveïdor` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
